#ifndef DMA_H
#define DMA_H
#include "std_types.h"

/* ================= Types ================= */

#define DMA1_NUM 0U
#define DMA2_NUM 1U

#define STREAM0_NUM 0U
#define STREAM1_NUM 1U
#define STREAM2_NUM 2U
#define STREAM3_NUM 3U
#define STREAM4_NUM 4U
#define STREAM5_NUM 5U
#define STREAM6_NUM 6U
#define STREAM7_NUM 7U

#define CHANAL0_NUM 0U
#define CHANAL1_NUM 1U
#define CHANAL2_NUM 2U
#define CHANAL3_NUM 3U
#define CHANAL4_NUM 4U
#define CHANAL5_NUM 5U
#define CHANAL6_NUM 6U
#define CHANAL7_NUM 7U

// EVENT_enu_t event = (DMA_NUM<<6U)&(STREAM_NUM<<3U)&(CHANAL_NUM<<0U)
typedef enum
{
    /* ================= USART1 (DMA2, Channel 4) ================= */
    DMA_USART1_RX_DMA2_STREAM2_CHANNEL4 = ((DMA2_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL4_NUM)),
    DMA_USART1_RX_DMA2_STREAM5_CHANNEL4 = ((DMA2_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL4_NUM)),
    DMA_USART1_TX_DMA2_STREAM7_CHANNEL4 = ((DMA2_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL4_NUM)),

    /* ================= USART2 (DMA1, Channel 4) ================= */
    DMA_USART2_RX_DMA1_STREAM5_CHANNEL4 = ((DMA1_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL4_NUM)),
    DMA_USART2_TX_DMA1_STREAM6_CHANNEL4 = ((DMA1_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL4_NUM)),

    /* ================= USART6 (DMA2, Channel 5) ================= */
    DMA_USART6_RX_DMA2_STREAM1_CHANNEL5 = ((DMA2_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL5_NUM)),
    DMA_USART6_RX_DMA2_STREAM2_CHANNEL5 = ((DMA2_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL5_NUM)),
    DMA_USART6_TX_DMA2_STREAM6_CHANNEL5 = ((DMA2_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL5_NUM)),
    DMA_USART6_TX_DMA2_STREAM7_CHANNEL5 = ((DMA2_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL5_NUM)),

    /* ================= SPI1 (DMA2, Channel 3) ================= */
    DMA_SPI1_RX_DMA2_STREAM0_CHANNEL3 = ((DMA2_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL3_NUM)),
    DMA_SPI1_RX_DMA2_STREAM2_CHANNEL3 = ((DMA2_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL3_NUM)),
    DMA_SPI1_TX_DMA2_STREAM3_CHANNEL3 = ((DMA2_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL3_NUM)),
    DMA_SPI1_TX_DMA2_STREAM5_CHANNEL3 = ((DMA2_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL3_NUM)),

    /* ================= SPI2 (DMA1, Channel 0) ================= */
    DMA_SPI2_RX_DMA1_STREAM3_CHANNEL0 = ((DMA1_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL0_NUM)),
    DMA_SPI2_TX_DMA1_STREAM4_CHANNEL0 = ((DMA1_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL0_NUM)),

    /* ================= SPI3 (DMA1, Channel 0) ================= */
    DMA_SPI3_RX_DMA1_STREAM0_CHANNEL0 = ((DMA1_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL0_NUM)),
    DMA_SPI3_RX_DMA1_STREAM2_CHANNEL0 = ((DMA1_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL0_NUM)),
    DMA_SPI3_TX_DMA1_STREAM5_CHANNEL0 = ((DMA1_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL0_NUM)),
    DMA_SPI3_TX_DMA1_STREAM7_CHANNEL0 = ((DMA1_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL0_NUM)),

    /* ================= SPI4 (DMA2, Channel 4 & 5) ================= */
    DMA_SPI4_RX_DMA2_STREAM0_CHANNEL4 = ((DMA2_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL4_NUM)),
    DMA_SPI4_TX_DMA2_STREAM1_CHANNEL4 = ((DMA2_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL4_NUM)),
    DMA_SPI4_RX_DMA2_STREAM3_CHANNEL5 = ((DMA2_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL5_NUM)),
    DMA_SPI4_TX_DMA2_STREAM4_CHANNEL5 = ((DMA2_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL5_NUM)),

    /* ================= I2C1 (DMA1, Channel 1) ================= */
    DMA_I2C1_RX_DMA1_STREAM0_CHANNEL1 = ((DMA1_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL1_NUM)),
    DMA_I2C1_RX_DMA1_STREAM5_CHANNEL1 = ((DMA1_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL1_NUM)),
    DMA_I2C1_TX_DMA1_STREAM6_CHANNEL1 = ((DMA1_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL1_NUM)),
    DMA_I2C1_TX_DMA1_STREAM7_CHANNEL1 = ((DMA1_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL1_NUM)),

    /* ================= I2C2 (DMA1, Channel 7) ================= */
    DMA_I2C2_RX_DMA1_STREAM2_CHANNEL7 = ((DMA1_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL7_NUM)),
    DMA_I2C2_RX_DMA1_STREAM3_CHANNEL7 = ((DMA1_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL7_NUM)),
    DMA_I2C2_TX_DMA1_STREAM7_CHANNEL7 = ((DMA1_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL7_NUM)),

    /* ================= I2C3 (DMA1 / DMA2 mixed) ================= */
    DMA_I2C3_RX_DMA1_STREAM1_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL3_NUM)),
    DMA_I2C3_RX_DMA1_STREAM2_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL3_NUM)),
    DMA_I2C3_TX_DMA1_STREAM4_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL3_NUM)),
    DMA_I2C3_TX_DMA2_STREAM5_CHANNEL6 = ((DMA2_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL6_NUM)),

    /* ================= I2S2 ================= */
    DMA_I2S2_EXT_RX_DMA1_STREAM3_CHANNEL2 = ((DMA1_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL2_NUM)),
    DMA_I2S2_EXT_TX_DMA1_STREAM4_CHANNEL2 = ((DMA1_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL2_NUM)),

    /* ================= I2S3 ================= */
    DMA_I2S3_EXT_RX_DMA1_STREAM0_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL3_NUM)),
    DMA_I2S3_EXT_RX_DMA1_STREAM2_CHANNEL2 = ((DMA1_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL2_NUM)),
    DMA_I2S3_EXT_TX_DMA1_STREAM5_CHANNEL2 = ((DMA1_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL2_NUM)),

    /* ================= TIM1 (DMA2) ================= */
    DMA_TIM1_CH1_DMA2_STREAM1_CHANNEL6  = ((DMA2_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_CH1_DMA2_STREAM3_CHANNEL6  = ((DMA2_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_CH2_DMA2_STREAM2_CHANNEL6  = ((DMA2_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_CH2_DMA2_STREAM6_CHANNEL0  = ((DMA2_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL0_NUM)),
    DMA_TIM1_CH3_DMA2_STREAM6_CHANNEL6  = ((DMA2_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_CH4_DMA2_STREAM4_CHANNEL6  = ((DMA2_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_TRIG_DMA2_STREAM0_CHANNEL6 = ((DMA2_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_TRIG_DMA2_STREAM4_CHANNEL6 = ((DMA2_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_COM_DMA2_STREAM4_CHANNEL6  = ((DMA2_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM1_UP_DMA2_STREAM5_CHANNEL6   = ((DMA2_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL6_NUM)),

    /* ================= TIM2 (DMA1, Channel 3) ================= */
    DMA_TIM2_UP_DMA1_STREAM1_CHANNEL3  = ((DMA1_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL3_NUM)),
    DMA_TIM2_UP_DMA1_STREAM7_CHANNEL3  = ((DMA1_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL3_NUM)),
    DMA_TIM2_CH1_DMA1_STREAM5_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL3_NUM)),
    DMA_TIM2_CH2_DMA1_STREAM6_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL3_NUM)),
    DMA_TIM2_CH3_DMA1_STREAM1_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL3_NUM)),
    DMA_TIM2_CH4_DMA1_STREAM6_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL3_NUM)),
    DMA_TIM2_CH4_DMA1_STREAM7_CHANNEL3 = ((DMA1_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL3_NUM)),

    /* ================= TIM3 (DMA1, Channel 5) ================= */
    DMA_TIM3_CH1_DMA1_STREAM4_CHANNEL5  = ((DMA1_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL5_NUM)),
    DMA_TIM3_CH2_DMA1_STREAM5_CHANNEL5  = ((DMA1_NUM<<6U)|(STREAM5_NUM<<3U)|(CHANAL5_NUM)),
    DMA_TIM3_CH3_DMA1_STREAM7_CHANNEL5  = ((DMA1_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL5_NUM)),
    DMA_TIM3_CH4_DMA1_STREAM2_CHANNEL5  = ((DMA1_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL5_NUM)),
    DMA_TIM3_UP_DMA1_STREAM2_CHANNEL5   = ((DMA1_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL5_NUM)),
    DMA_TIM3_TRIG_DMA1_STREAM4_CHANNEL5 = ((DMA1_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL5_NUM)),

    /* ================= TIM4 (DMA1, Channel 2) ================= */
    DMA_TIM4_CH1_DMA1_STREAM0_CHANNEL2 = ((DMA1_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL2_NUM)),
    DMA_TIM4_CH2_DMA1_STREAM3_CHANNEL2 = ((DMA1_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL2_NUM)),
    DMA_TIM4_CH3_DMA1_STREAM7_CHANNEL2 = ((DMA1_NUM<<6U)|(STREAM7_NUM<<3U)|(CHANAL2_NUM)),
    DMA_TIM4_UP_DMA1_STREAM6_CHANNEL2  = ((DMA1_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL2_NUM)),

    /* ================= TIM5 (DMA1, Channel 6) ================= */
    DMA_TIM5_CH1_DMA1_STREAM2_CHANNEL6  = ((DMA1_NUM<<6U)|(STREAM2_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_CH2_DMA1_STREAM4_CHANNEL6  = ((DMA1_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_CH3_DMA1_STREAM0_CHANNEL6  = ((DMA1_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_CH4_DMA1_STREAM1_CHANNEL6  = ((DMA1_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_CH4_DMA1_STREAM3_CHANNEL6  = ((DMA1_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_TRIG_DMA1_STREAM1_CHANNEL6 = ((DMA1_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_TRIG_DMA1_STREAM3_CHANNEL6 = ((DMA1_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_UP_DMA1_STREAM0_CHANNEL6   = ((DMA1_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL6_NUM)),
    DMA_TIM5_UP_DMA1_STREAM6_CHANNEL6   = ((DMA1_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL6_NUM)),

    /* ================= ADC1 (DMA2, Channel 0) ================= */
    DMA_ADC1_DMA2_STREAM0_CHANNEL0 = ((DMA2_NUM<<6U)|(STREAM0_NUM<<3U)|(CHANAL0_NUM)),
    DMA_ADC1_DMA2_STREAM4_CHANNEL0 = ((DMA2_NUM<<6U)|(STREAM4_NUM<<3U)|(CHANAL0_NUM)),

    /* ================= SDIO (DMA2, Channel 4) ================= */
    DMA_SDIO_DMA2_STREAM3_CHANNEL4 = ((DMA2_NUM<<6U)|(STREAM3_NUM<<3U)|(CHANAL4_NUM)),
    DMA_SDIO_DMA2_STREAM6_CHANNEL4 = ((DMA2_NUM<<6U)|(STREAM6_NUM<<3U)|(CHANAL4_NUM)),

    /* ================= Memory-to-Memory (DMA2 only) ================= */
    DMA_MEM2MEM_DMA2_STREAM1_CHANNEL1 = ((DMA2_NUM<<6U)|(STREAM1_NUM<<3U)|(CHANAL1_NUM))

} DMA_Request_t;
typedef enum
{
    DMA_OK = 0,
    DMA_BUSY,
    DMA_ERROR
} DMA_Status_t;

typedef enum
{
    
    DMA_DIR_PERIPH_TO_MEM,
    DMA_DIR_MEM_TO_PERIPH,
    DMA_DIR_MEM_TO_MEM
} DMA_Direction_t;

typedef enum
{
    DMA_DATA_WIDTH_8BIT = 0,
    DMA_DATA_WIDTH_16BIT,
    DMA_DATA_WIDTH_32BIT
} DMA_DataWidth_t;

typedef enum
{
    DMA_INC_DISABLE = 0,
    DMA_INC_ENABLE
} DMA_IncrementMode_t;

typedef enum
{
    DMA_PRIORITY_LOW = 0,
    DMA_PRIORITY_MEDIUM,
    DMA_PRIORITY_HIGH,
    DMA_PRIORITY_VERY_HIGH
} DMA_Priority_t;

typedef enum
{
    DMA_MODE_NORMAL = 0,
    DMA_MODE_CIRCULAR
} DMA_Mode_t;
typedef enum
{
    DMA_INT_TC = 0,   /* Transfer Complete */
    DMA_INT_HT,       /* Half Transfer */
    DMA_INT_TE        /* Transfer Error */
} DMA_InterruptType_t;
typedef enum
{
    DMA_FLOW_CTRL_DMA = 0,
    DMA_FLOW_CTRL_PERIPHERAL
} DMA_FlowController_t;
typedef void (*DMA_Callback_t)(uint8_t Dma, uint8_t Stream);

// Add this field to your DMA_Config_t struct
typedef struct {
    DMA_FlowController_t FlowController;  
    DMA_Direction_t Direction;
    DMA_DataWidth_t MemoryDataWidth;
    DMA_DataWidth_t PeripheralDataWidth;
    DMA_IncrementMode_t MemoryInc;
    DMA_IncrementMode_t PeripheralInc;
    DMA_Priority_t Priority;
    DMA_Mode_t Mode;
    uint32_t *MemoryAddress;
    uint32_t *PeripheralAddress;
    uint16_t DataLength;
    uint32_t Request;
} DMA_Config_t;



/* ================= APIs ================= */

/* Initialize DMA peripheral */
void DMA_Init(DMA_Config_t *config);

/* Start DMA transfer */
DMA_Status_t DMA_Start(DMA_Config_t *config);

/* Get number of remaining data */
signed int DMA_GetTransferDataNum(DMA_Config_t *config);

/* Get transfer status */
DMA_Status_t DMA_GetTransferStatus(DMA_Config_t *config);

/* Memory copy using DMA */
DMA_Status_t DMA_MemCpy(uint32_t *dest, uint32_t *src, uint16_t length);

#endif /* DMA_H */
